#!/bin/sh

echo "Running pre-commit..."
echo
./../../tests/run-test-pre-com.sh

# $? stores exit value of the last command
if [ $? -ne 0 ]; then
 	echo "You must pass 30% of tests before commit!"
	echo "No commit has been made."
 	exit 1
fi

echo "Your commit is done!"
